area:
  pixel_scale: 50
  screen_size:
  - 450
  - 450
display:
  agent_size: 4
  control_line_size: 2
  fire_size: 2
  rescale_factor: 2
environment:
  moisture: 0.009
fire:
  diagonal_spread: false
  fire_initial_position:
    random:
      seed: 8835
    static:
      position:
      - 33
      - 32
    type: static
  max_fire_duration: 99
mitigation:
  ros_attenuation: false
operational:
  height: 2000
  latitude: 45.337570669856724
  longitude: -111.11640653849565
  resolution: 30
  width: 2000
  year: 2019
simulation:
  data_type: npy
  draw_spread_graph: false
  headless: false
  record: true
  runtime: 26h
  save_data: true
  sf_home: ~/.simfire
  update_rate: 1
terrain:
  fuel:
    burn_probability:
      functional:
        function: gaussian
        gaussian:
          amplitude: 335
          mu_x: 68
          mu_y: 33
          sigma_x: 69
          sigma_y: 55
        perlin:
          lacunarity: 2.25
          octaves: 3
          persistence: 0.52
          range_max: 279
          range_min: 57
          seed: 3908
      type: operational
    functional:
      chaparral:
        seed: 7944
      function: chaparral
    type: operational
  topography:
    functional:
      function: perlin
      gaussian:
        amplitude: 585
        mu_x: 43
        mu_y: 56
        sigma_x: 61
        sigma_y: 52
      perlin:
        lacunarity: 2.19
        octaves: 4
        persistence: 0.66
        range_max: 348.6216250802886
        range_min: 91.26161421310061
        seed: 4327
    type: operational
wind:
  cfd:
    diffusion: 0.6430086086542165
    direction: southwest
    iterations: 4
    result_accuracy: 1
    scale: 3
    speed: 10
    time_to_train: 578
    timestep_dt: 1.2262150902459767
    viscosity: 2.3507824931579068e-05
  function: perlin
  perlin:
    direction:
      lacunarity: 1.54
      octaves: 4
      persistence: 0.95
      range_max: 334.7310567942919
      range_min: 3.690693189176363
      scale: 1755
      seed: 4353
    speed:
      lacunarity: 2.08
      octaves: 4
      persistence: 0.64
      range_max: 46
      range_min: 10
      scale: 139
      seed: 8285
  simple:
    direction: 246
    speed: 77
