area:
  pixel_scale: 50
  screen_size:
  - 450
  - 450
display:
  agent_size: 4
  control_line_size: 2
  fire_size: 2
  rescale_factor: 2
environment:
  moisture: 0.003
fire:
  diagonal_spread: false
  fire_initial_position:
    random:
      seed: 3464
    static:
      position:
      - 22
      - 24
    type: static
  max_fire_duration: 36
mitigation:
  ros_attenuation: false
operational:
  height: 2000
  latitude: 43.68533028810687
  longitude: -117.63597852416004
  resolution: 30
  width: 2000
  year: 2021
simulation:
  data_type: npy
  draw_spread_graph: false
  headless: false
  record: true
  runtime: 17h
  save_data: true
  sf_home: ~/.simfire
  update_rate: 1
terrain:
  fuel:
    burn_probability:
      functional:
        function: gaussian
        gaussian:
          amplitude: 404
          mu_x: 50
          mu_y: 57
          sigma_x: 83
          sigma_y: 52
        perlin:
          lacunarity: 1.83
          octaves: 5
          persistence: 0.54
          range_max: 203
          range_min: 57
          seed: 3718
      type: operational
    functional:
      chaparral:
        seed: 6838
      function: chaparral
    type: operational
  topography:
    functional:
      function: perlin
      gaussian:
        amplitude: 496
        mu_x: 48
        mu_y: 22
        sigma_x: 98
        sigma_y: 62
      perlin:
        lacunarity: 1.92
        octaves: 5
        persistence: 0.63
        range_max: 230.67340203072712
        range_min: 91.7506793329791
        seed: 7783
    type: operational
wind:
  cfd:
    diffusion: 0.8702604255726208
    direction: northeast
    iterations: 2
    result_accuracy: 1
    scale: 1
    speed: 5
    time_to_train: 1444
    timestep_dt: 0.5941187614069873
    viscosity: 6.300676841370582e-05
  function: simple
  perlin:
    direction:
      lacunarity: 1.93
      octaves: 4
      persistence: 0.96
      range_max: 274.9918099478076
      range_min: 42.63381603056045
      scale: 1381
      seed: 4758
    speed:
      lacunarity: 2.5
      octaves: 3
      persistence: 0.74
      range_max: 42
      range_min: 7
      scale: 424
      seed: 4675
  simple:
    direction: 211
    speed: 25
