area:
  pixel_scale: 50
  screen_size:
  - 450
  - 450
display:
  agent_size: 4
  control_line_size: 2
  fire_size: 2
  rescale_factor: 2
environment:
  moisture: 0.004
fire:
  diagonal_spread: true
  fire_initial_position:
    random:
      seed: 9058
    static:
      position:
      - 39
      - 44
    type: static
  max_fire_duration: 12
mitigation:
  ros_attenuation: false
operational:
  height: 2000
  latitude: 49.42415387984483
  longitude: -108.05139825179107
  resolution: 30
  width: 2000
  year: 2020
simulation:
  data_type: npy
  draw_spread_graph: false
  headless: false
  record: true
  runtime: 11h
  save_data: true
  sf_home: ~/.simfire
  update_rate: 1
terrain:
  fuel:
    burn_probability:
      functional:
        function: gaussian
        gaussian:
          amplitude: 417
          mu_x: 25
          mu_y: 55
          sigma_x: 100
          sigma_y: 85
        perlin:
          lacunarity: 2.18
          octaves: 5
          persistence: 0.62
          range_max: 289
          range_min: 93
          seed: 2957
      type: operational
    functional:
      chaparral:
        seed: 8026
      function: chaparral
    type: operational
  topography:
    functional:
      function: perlin
      gaussian:
        amplitude: 272
        mu_x: 40
        mu_y: 62
        sigma_x: 61
        sigma_y: 41
      perlin:
        lacunarity: 2.79
        octaves: 3
        persistence: 0.8
        range_max: 263.5701099225929
        range_min: 85.4747699026627
        seed: 2536
    type: operational
wind:
  cfd:
    diffusion: 0.44942157888884904
    direction: southwest
    iterations: 4
    result_accuracy: 1
    scale: 3
    speed: 29
    time_to_train: 567
    timestep_dt: 0.7194003994420715
    viscosity: 1.0489133641659597e-05
  function: simple
  perlin:
    direction:
      lacunarity: 1.14
      octaves: 5
      persistence: 0.86
      range_max: 320.07078757106166
      range_min: 29.44867162188295
      scale: 1698
      seed: 3626
    speed:
      lacunarity: 1.76
      octaves: 4
      persistence: 0.58
      range_max: 36
      range_min: 11
      scale: 130
      seed: 1620
  simple:
    direction: 227
    speed: 19
