image: "python:3.9"

before_script:
  - python --version
  # Adding this because furo gets a wheel validation error for the 1.4.1 install
  - export POETRY_VERSION=1.4.0
  - curl -sSkL https://install.python-poetry.org | python -
  - export PATH=$PATH:$HOME/.local/bin
  - poetry --version

stages:
  - Static Analysis
  - Security
  - Documentation
  - Docker

###################
# Static Analysis #
###################
flake8:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry install --only dev
    - poetry run flake8 .
  needs: []
  only:
    - merge_requests

black:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry install --only dev
    - poetry run black --check ./
  needs: []
  only:
    - merge_requests

# mypy:
#   stage: Static Analysis
#   tags:
#     - lslab2
#   script:
#     - poetry install --only dev
#     - poetry run mypy .
#   needs: []
#   only:
#     - merge_requests

isort:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry install --only dev
    - poetry run isort --check --trailing-comma -m=3 .
  needs: []
  only:
    - merge_requests

############
# Security #
############
bandit:
  stage: Security
  tags:
    - lslab2
  script:
    - pip install bandit
    - bandit -r .
  needs: []
  only:
    - merge_requests

################
# GitLab Pages #
################
.pages:
  script:
    - pip install -U sphinx sphinx-autoapi sphinx-rtd-theme myst-parser furo
    - sphinx-build -d docs/build/doctrees docs/source docs/build/html
    - mv docs/build/html public/

test-pages:
  stage: Documentation
  tags:
    - lslab2
  extends: .pages
  needs: []
  artifacts:
    expose_as: 'HTML Documentation'
    paths:
      - public/
    expire_in: 1 week
  only:
    - merge_requests

pages:
  stage: Documentation
  tags:
    - lslab2
  extends: .pages
  artifacts:
    paths:
      - public
  only:
    - main

#########
# Build #
#########
.build:
  script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}
    - docker login butler.mitre.org --username ${HARBOR_SIMHARNESS_USER} --password ${HARBOR_SIMHARNESS_PASS}
    - docker build --build-arg RAY_VERSION=${RAY_VERSION} -f docker/simple.dockerfile -t butler.mitre.org/fireline/simharness2:simple-${RAY_VERSION} .
    - docker push butler.mitre.org/fireline/simharness2:simple-${RAY_VERSION}
    - docker build --build-arg RAY_VERSION=${RAY_VERSION} -f docker/simple-grafana-prometheus.dockerfile -t butler.mitre.org/fireline/simharness2:simple-grafana-prometheus-${RAY_VERSION} .
    - docker push butler.mitre.org/fireline/simharness2:simple-grafana-prometheus-${RAY_VERSION}

simple-2.4.0:
  stage: Docker
  tags:
    - lslab2
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  before_script:
    - docker --version
  variables:
    RAY_VERSION: 2.4.0
  extends: .build
  only:
    - dev
    - main

simple-2.5.1:
  stage: Docker
  tags:
    - lslab2
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  before_script:
    - docker --version
  variables:
    RAY_VERSION: 2.5.1
  extends: .build
  only:
    - dev
    - main

simple-2.6.2:
  stage: Docker
  tags:
    - lslab2
  image: docker:20.10.16-dind
  services:
    - docker:20.10.16-dind
  before_script:
    - docker --version
  variables:
    RAY_VERSION: 2.6.2
  extends: .build
  only:
    - dev
    - main
