exclude: 'assets/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-poetry
        name: check Poetry TOML
        description: Validates the structure of the pyproject.toml file
        entry: poetry check
        language: system
        pass_filenames: false
        files: pyproject.toml
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      # - id: mypy
      #   name: mypy
      #   exclude: /_tests/
      #   exclude: tests/
      #   language: python
      #   entry: mypy
      #   args: [--config-file, pyproject.toml]
      #   # use your preferred Python version
      #   types: [python]
      - id: isort
        name: isort
        language: python
        entry: isort
        args: [--trailing-comma, -m=3]
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      additional_dependencies: ["tomli"]
