defaults:
  - simulation: default
  - training: default
  - environment: default
  - framework: default
  - rollouts: default
  - evaluation: default
  - exploration: default
  # - debugging: default
  - resources: default
  - hydra: default
  - tunables: default
  - _self_

cli:
  # Specify the run mode. Supported options: train, tune, view
  mode: train
  # Specify the root directory used to save data for the experiment.
  data_dir: ??
algo:
  name: PPO
  # The path (str) to the checkpoint directory to use.
  checkpoint_path: null
# Specify configuration used to create the ray.air.CheckpointConfig object
checkpoint:
  # Frequency at which to save checkpoints (in terms of training iterations)
  checkpoint_frequency: 20
  # Number of checkpoints to keep
  num_to_keep: null
stop_conditions:
  training_iteration: 4
  timesteps_total: 2000000000
  episodes_total: 1000000
  episode_reward_mean: 10000000
debugging:
  log_level: INFO
  log_sys_usage: True
  seed: 2000
  logger_config:
    type:
      _target_: hydra.utils.get_class
      path: ray.tune.logger.UnifiedLogger
    logdir: ${hydra:run.dir}
